### PR TITLE
Fix typo in searchquery for "should" query part

### PR DESCRIPTION
**Pull request by geoffreybergdoll**

### CODE REVIEW

**Comment by brett19** [comment]
Hey @geoffreybergdoll,
Would you be able to sign the CLA so we can pull this in?
Cheers, Brett

**Comment by geoffreybergdoll** [comment]
Hi Brett,
Done.
Best,
Geoffrey

**Comment by ingenthr** [comment]
Thanks @geoffreybergdoll !

**Comment by brett19** [comment]
Hey @geoffreybergdoll ,
Can you check your Gerrit account to ensure the email from your commit is attached?  It doesn't look like Gerrit is able to link this PR to your Gerrit account, it's usually simply fixed by checking the emails on your Gerrit account. :)
Cheers, Brett

**Comment by geoffreybergdoll** [comment]
There wasn’t any email address.
I added the address used in my GitHub account to do the PR.
It should work now.

Best,

Geoffrey

**Comment by brett19** [comment]
*poking to see if the bot see it*

**Comment by ingenthr** [comment]
Thanks @geoffreybergdoll 

> There wasn’t any email address.

Yeah, that's normal.  Because of how the auth works on gerrit (review.couchbase.com) it cannot automatically populate the email address.  But we need the email address to associate the CLA with the change the bot pulls over.  Sorry for the need of the additional step, but it's a limitation owing to privacy we cannot avoid at the moment.

Thanks for filling it in!

**Comment by brett19** [comment]
Woops.

**Comment by brett19** [comment]
Merged.  Thanks @geoffreybergdoll !

**Pull request closed without merging**
