### PR TITLE
Update prebuild to 6.0.0

### PR DESCRIPTION
**Pull request by sdepold**
Updating prebuild should fix the installation with yarn https://github.com/mafintosh/prebuild/issues/132

### CODE REVIEW

**Comment by sdepold** [comment]
I think I signed it?!

**Comment by ingenthr** [comment]
@sdepold, sometimes the problem is a mismatched email address. In this case, it looks like you didn't set an email address or it didn't come over from your identity provider at review.couchbase.org.

Can you register your email at http://review.couchbase.org/#/settings/contact after logging in?  That should complete the CLA.  The pull request email needs to match the person accepting the CLA for reasonable reasons.

@brett19 is the above all correct?

**Comment by brett19** [comment]
Hey @sdepold ,
Have you had any luck with correcting your email on Gerrit?
Cheers, Brett

**Comment by sdepold** [comment]
Should be fine now?!

**Comment by brett19** [comment]
Hey @sdepold,
The bot scans the PR whenever a new comment is entered, or a new user signs the CLA.  I suspect that the email address on the PR may not be what you expect, you can use git log to view it.
Cheers, Brett

**Comment by sdepold** [comment]
Maybe now?

**Comment by ingenthr** [comment]
I looked, and your email address is in there.  @brett19, any thought on why the bot didn't pick it up?

@sdepold thanks for fixing that.  we'll get it into gerrit.  we were doing some maintenance earlier today, so that may have had an impact here.

**Comment by sdepold** [comment]
@ingenthr @brett19 One additional note on that topic: Originally I commit the change through the Github Web UI which apparently uses the email address `<username>@users.noreply.github.com`

**Comment by ingenthr** [comment]
Thanks for the contribution @sdepold!   Our apologies for the confusion with the email match and the bot.  @brett19 suggested we make some changes to make it clear which email address the bot sees in the commit, so we'll probably do that going forward.  If you have any other thoughts/feedback on what worked/didn't work, by all means, let us know.

Thanks again.

**Comment by sdepold** [comment]
Any chance to get a new release?

**Pull request closed without merging**
