### PR TITLE
Update nan to 1.8.4

### PR DESCRIPTION
**Pull request by corbinu**
This enables iojs 2.x.x it is just a very small change to remove a warning and a nan bump. Honestly would probably be easier to just just redo yourself but needed it for my work so figured I would submit

### CODE REVIEW

**Comment by martinmicunda** [comment]
+1

**Comment by anishcodes** [comment]
+1

**Comment by corbinu** [comment]
If it helps you both in the meantime I am maintaining a fork in npm as @corbinu/couchbase

I am using it for my app and will probably continue to maintain merging this module at each release, but with io.js support

**Comment by anishcodes** [comment]
@corbinu ... That is gr8!

Btw, seems like they have already fixed this (https://issues.couchbase.com/browse/JSCBC-232).
Not sure where, as I am new to development with couchbase. Maybe they maintain a private branch for paid customers?

**Comment by corbinu** [comment]
We shall see ... Brett is right Is very hard to keep up with iojs as V8 keeps changing.

I totally understand his not wanting to have to QA and cut a release every few weeks that's why I put up my version for my code and will just issue pull requests here as new versions come out.

**Comment by ingenthr** [comment]
All of our source is open though you may occasionally see a source change for enterprise subscribers.  I'm sure @brett19x has plans here.

Matt (from Couchbase)

**Comment by alubbe** [comment]
+1, see https://github.com/couchbase/couchnode/pull/39

**Comment by corbinu** [comment]
Since the 2.0.9 release is on npm (though not tagged here yet). I merged 2.0.9 into my scoped repo and am closing.

**Pull request closed without merging**
