### PR TITLE
Switch from JSHint to ESlint 2

### PR DESCRIPTION
**Pull request by corbinu**
ESlint is a newer pluggable linter that does both the job of JSHint and JSCS (the JSCS team has actually joined the ESLint team)

This PR is both a translation of the existing JSHint rules and a set of fixes based on issues found. It is structured so that if there is a rule you want changed it should be easy for me to rollback the commit and update the .eslintrc

Let me know if you have any questions or want any rule changes

### CODE REVIEW

**Comment by brett19** [comment]
Hey @corbinu,
I am definitely interested in getting this in.  We should be able to get it hopefully merged before our next release.
Cheers, Brett

**Comment by corbinu** [comment]
@brett19 Cool I will update it to match the latest changes.

**Comment by englercj** [comment]
Just a heads up, eslint released v3 recently: http://eslint.org/blog/2016/07/eslint-v3.0.0-released

**Comment by brett19** [comment]
Hey @corbinu ,
Please let me know when you have update this to the latest.  Providing all tests still pass (specifically, linting tests in the MakeFile), then I will merge it!
Cheers, Brett

**Comment by corbinu** [comment]
Sure give me a day or two and will update (work work demanding my time)

Get Outlook for iOS




On Tue, Jul 12, 2016 at 11:49 AM -0700, "Brett Lawson" <notifications@github.com> wrote:












Hey @corbinu ,

Please let me know when you have update this to the latest.  Providing all tests still pass (specifically, linting tests in the MakeFile), then I will merge it!

Cheers, Brett

**Comment by brett19** [comment]
I am going to close this PR for now and we can reopen it once the update is complete 👍

**Pull request closed without merging**
