### PR TITLE
Access LookupInBuilder

### PR DESCRIPTION
**Pull request by sm2017**
I need to access LookupInBuilder from outside
To promisify lookupIn

### CODE REVIEW

**Comment by sm2017** [comment]
@couchbase I already signed CLA

**Comment by brett19** [comment]
Hey @sm2017 ,
Would you be able to check your Gerrit settings and confirm the email address indicated above is attached to the account you signed the CLA with?
Cheers, Brett

**Comment by sm2017** [comment]
I repead github oauth author again , and gerrit signed in me , and shown my username at top right corner of page
But the email address is empty in Gerrit setting

**Comment by brett19** [comment]
Hey @sm2017, inside your Gerrit Settings, there is a button to add additional email addresses linked to your account.  Please link the address above to have the patch pulled through!  Cheers, Brett

**Comment by sm2017** [comment]
Done

**Comment by brett19** [comment]
Hey @sm2017 ,
I'll get this merged before the next release.
P.S. Our system still doesn't see you having signed our CLA.  Any chance you could double-check your gerrit email and CLA settings?
Cheers, Brett

**Comment by brett19** [comment]
Hey @sm2017,
I'm going to close this and manually update/include your requested change through here:
https://issues.couchbase.com/browse/JSCBC-509
http://review.couchbase.org/100151
Cheers, Brett

**Pull request closed without merging**
