### PR TITLE
Do not JSON.parse id_range in MockBucket._execView

### PR DESCRIPTION
**Pull request by Bloutiouf**
startkey_docid and endkey_docid are either undefined, or strings containing a doc id. As such, they shouldn't be parsed. This is already the behavior of the real implementation. The mock implementation is failing my tests, although it works with the real one.

The change for group_level is only a simplification in JS.

### CODE REVIEW

**Comment by Bloutiouf** [comment]
I've found another difference: results were sorted only by key, whereas the should be sorted by key and then by id.

**Comment by Bloutiouf** [comment]
Another difference spotted, sorting an array key with a null item was wrong.

As far as I can tell, your unit tests don't test the queries' results, it should be a nice thing to add ;)

**Comment by Bloutiouf** [comment]
It seems you don't check for query parameters validity. Here are some.

Do you give feedback sometimes? I feel alone here.

**Comment by ingenthr** [comment]
hey @Bloutiouf, we definitely give feedback!  apologies for missing this!

our workflow usually has us run things through gerrit at http://review.couchbase.com usually.  The rundown on how to do so is here:
http://www.couchbase.com/wiki/display/couchbase/Contributing+Changes

**Comment by Bloutiouf** [comment]
Ok so it wasn't the good place. I can't see the number of people in the group `CLA Accepted - Individual`, but as there are many open PR in GitHub, you should investigate the possibility of merging them into your main repository. I'm sure you can easily add a Change-Id with a script by pulling the PR branch and interactively rebasing the branch to edit the commit messages. Though one thing I'm not confident with is the automatic mapping GitHub user -> Gerrit user, you might need a manual step here.

Or it's not possible, then you should disable the feature *Issues* in the GitHub repository settings, and change your `CONTRIBUTING.md` because the instructions here are not the same.

Anyway, the root cause for these fixes is that the tests for the mock implementation don't check against the validity of input parameters and the correctness of query responses. You should add these tests, as for now, the two implementations have eventually a significant different behavior regarding queries.

As a side note, it's too bad that the error reporting does not preserve the actual error. I mean, in the last commit of this PR, I added

```js
return callback(new Error('query_parse_error: Invalid value for integer parameter: "' + options.skip.toString() + '"'));
```

because that's what the real implementation would send. But the real server sends

```js
{
  "error": "query_parse_error",
  "reason": "Invalid value for integer parameter: \"xxx\""
}
```

and imho it's better to send the following error (code for the real implementation), because it will be easier to handle the error if the error code is preserved without concatenating it with the reason string

```js
var err;
try {
  var body = JSON.parse(response.body);
  err = new Error(body.reason);
  err.code = body.error;
} catch (err) {
  return callback(response.body);
}
return callback(err);
```

Note the `try/catch`, it happens sometimes (I can't recall exactly when) that the server does not respond a JSON error, but your client is actually expecting a JSON response, so there is in your code a `JSON.parse` that is non-catchable and it will make the node process abort.

**Comment by Bloutiouf** [comment]
I found a couple of bugs in the past weeks.

BTW, I tried to start the PR procedure on Gerrit, but it registered with my Google OpenID, which is now deprecated, so I can't log in anymore.

**Comment by ingenthr** [comment]
I think @brett19 will be able to help, and he's assigned already.

**Comment by Bloutiouf** [comment]
I forgot to integrate one fix yesterday.

**Comment by Bloutiouf** [comment]
Any news?

**Comment by Bloutiouf** [comment]
Good holidays everyone? I'm sad, I didn't received any post card from you neither.

BTW your module does not work with Node.js 4.1.0 (currently the latest version).

**Comment by brett19** [comment]
Hey Bloutiouf!
These are all really useful changes.  Sorry for the delay in getting back to you, it appears that GitHub was not notifying me of this PR.  I'm looking at getting this stuff into Gerrit today.
Cheers, Brett

**Comment by Bloutiouf** [comment]
Hey Brett! Good to finally hear from you.

I tried recently to pull down the latest changes you made in the meanwhile, there were some conflicts. Hopefully you'll manage to merge them quickly.

**Comment by brett19** [comment]
remote:   http://review.couchbase.org/55301 Do not JSON.parse id_range in MockBucket._execView
remote:   http://review.couchbase.org/55302 Sort results by key and then by id in MockBucket._execView
remote:   http://review.couchbase.org/55303 Fix sort order fur null items in a array key in MockBucket._execView
remote:   http://review.couchbase.org/55304 Assert integer skip and limit values
remote:   http://review.couchbase.org/55305 Fix range: inclusive_end is true by default, as of Couchbase 3.0.0.
remote:   http://review.couchbase.org/55306 Fix mocked bucket.query: group was not taken into account.
remote:   http://review.couchbase.org/55307 Use qs for handling query strings.
remote:   http://review.couchbase.org/55308 startkey_docid is only relevant when the key is startkey.

**Comment by Bloutiouf** [comment]
The changes are not merged yet, Gerrit complains that it cannot merge.

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

Unfortunately it has been 7 days and we are still unable to confirm that you have signed our CLA.  We sincerely appreciate your submission and hope that you will register and resubmit this Pull Request in the future!

::SDKBOT/PR:timeout

**Comment by Bloutiouf** [comment]
I remember having signed the CLA, at the time when it was possible to log in Gerrit with Google OpenID.

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

Unfortunately it has been 7 days and we are still unable to confirm that you have signed our CLA.  We sincerely appreciate your submission and hope that you will register and resubmit this Pull Request in the future!

::SDKBOT/PR:timeout

**Pull request closed without merging**
