### PR TITLE
added flags back to store and get functions

### PR DESCRIPTION
**Pull request by AlmirKadric**
Currently the only way to operate on document flags is to implement the bucket-wide transcoder functions. However when the application itself already handles encoding/decoding (in our case for compatibility between many data stores), the transcoder functions become more of a nuisance than a feature. i.e. we already have serialised UTF-8 or Binary data and know what the data type should be, e.g. JSON, in this case we would like to set the flags directly as was available in couchnode v1.x.

This pull request re-implements this feature by allowing you to pass in the flags options arguments for all store operations and returns it as the last argument of get operation callbacks.

I tried to make the implementation as minimal and backwards compatible as possible.

### CODE REVIEW

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

To get this change in and collaborate in code review, please register on Gerrit and accept our CLA.  More detailed instructions are available here: http://developer.couchbase.com/open-source-projects#how-to-contribute-code.

Note: Please contact us if you have any issues registering with Gerrit!  If you are not registered after 7 days, the Pull Request will automatically be closed.

::SDKBOT/PR:no_cla

**Comment by AlmirKadric** [comment]
Hi @brett19 
I've registered with `http://review.couchbase.org` however I do not see this pull request inside the items list. I was told that you guys already have a system in place which pulls in pull requests from GitHub into Gerrit. Is this the case? Or do i need to follow the process outlined here:`http://www.couchbase.com/wiki/display/couchbase/Contributing+Changes` to get my work reviewed?

**Comment by brett19** [comment]
Transferred commit (838b7f8a452efa9a3646ac73620b53198d6a6405) to Couchbase Review site:
http://review.couchbase.org/#/c/59661

::SDKBOT/PR:created

**Comment by AlmirKadric** [comment]
@brett19 Thanks!!!! let me know if I need to do anything :+1:

**Comment by brett19** [comment]
Hey @AlmirKadric,
After looking at your PR a bit more, I see some potentially flaws in regards to what happens when the user specifies flags directly, but the transcoder has a different idea.  In these cases, I like to suggest that you use a passthru transcoder which accepts a tuple of values,flags and simply passes through that information.  This means that you should be able to use flags/values manually everywhere throughout your application without too much complication.  Let me know if you need any more information.
Cheers, Brett

**Comment by AlmirKadric** [comment]
Hi @brett19,
Though we could do the above, it is rather hackish. My main concern would be with the fact that the default transcoder function would be scrapped once we set it and that the get/set API input output behaviours would change for that bucket on a global level. This means that if we set anything from that point on without specifying the correct tuple structure {value, flags} it would throw an exception.

The reason we would have this is that we have wrapped couchbase (as we manage multiple datastore types) and when necessary the user has direct access to couchbase client as well. The only way to avoid this would be to replicate the code inside the default transcoder back into our pass-through functions and if we happen to pass in flags we change the behaviour.

Could you explain to me the issues with allowing a user to set the flags directly?
I have looked over the code and fail to see the issues you are mentioning.
The flags argument is completely optional, and if provided would override what is set by the encode function (decode is irrelevant).

**Comment by AlmirKadric** [comment]
@brett19 I also tested the above, and seems there is also a bug inside the transcoder.
Take the following pass-through code sample:
```
var encoder = function (value) {
	var transcoderDoc;
	if (typeof value === 'string' || value instanceof String) {
		transcoderDoc = { value: value, flags: 0 };
	} else if (value instanceof Buffer) {
		transcoderDoc = { value: value, flags: 4 };
	} else {
		if (value.value && value.flags) {
			transcoderDoc = { value: value.value, flags: value.flags };
		} else {
			try {
				transcoderDoc = { value: JSON.stringify(value), flags: 2 };
			} catch (error) {
				// TODO: NEED BETTER ERROR HANDLING HERE
				// NOTE: CHECK COUCHNOE NATIVE C CODE: `src/transcoder.cc`
				return;
			}
		}
	}

	console.log('ENCODER DOC:', transcoderDoc);
	return transcoderDoc;
};
var decoder = function (transcoderDoc) {
	console.log('DECODER DOC:', transcoderDoc);
	console.log('DECODER DOC:', (transcoderDoc.value || '').toString(), transcoderDoc.flags);
	return transcoderDoc;
};
_client.setTranscoder(encoder, decoder);
```

According to this, we should have the same behaviour as the default transcoder with the exception that if the encoder receives an object which contains the properties flags and value. In this instance we pass the value and flags along. However we end up with the following results:
SET OPERATION:
```
ENCODER DOC: { value: '{\n\t"meta": {\n\t\t"access": "admin",\n\t\t"user": {\n\t\t\t"id": "f7127157-0ed6-48b5-b0b6-5e78af4c369e",\n\t\t\t"engines": {\n\t\t\t\t"gameUsersGuest": "f7127157-0ed6-48b5-b0b6-5e78af4c369e"\n\t\t\t},\n\t\t\t"_eventsCount": 1,\n\t\t\t"_events": {}\n\t\t}\n\t},\n\t"actorId": "f7127157-0ed6-48b5-b0b6-5e78af4c369e",\n\t"language": "en",\n\t"key": "2RR5y0u4P14wAkbB",\n\t"clusterId": "base-centos-6-6:31736",\n\t"creationTime": 1455100279,\n\t"version": "0.1.0"\n}',
  flags: 1785950062 }
```

GET OPERATION:
```
DECODER DOC: { value: <Buffer 7b 22 76 61 6c 75 65 22 3a 22 7b 5c 6e 5c 74 5c 22 6d 65 74 61 5c 22 3a 20 7b 5c 6e 5c 74 5c 74 5c 22 61 63 63 65 73 73 5c 22 3a 20 5c 22 61 64 6d 69 ... >,
  flags: 33554432 }
DECODER DOC: {"value":"{\n\t\"meta\": {\n\t\t\"access\": \"admin\",\n\t\t\"user\": {\n\t\t\t\"id\": \"f7127157-0ed6-48b5-b0b6-5e78af4c369e\",\n\t\t\t\"engines\": {\n\t\t\t\t\"gameUsersGuest\": \"f7127157-0ed6-48b5-b0b6-5e78af4c369e\"\n\t\t\t},\n\t\t\t\"_eventsCount\": 1,\n\t\t\t\"_events\": {}\n\t\t}\n\t},\n\t\"actorId\": \"f7127157-0ed6-48b5-b0b6-5e78af4c369e\",\n\t\"language\": \"en\",\n\t\"key\": \"2RR5y0u4P14wAkbB\",\n\t\"clusterId\": \"base-centos-6-6:31736\",\n\t\"creationTime\": 1455100279,\n\t\"version\": \"0.1.0\"\n}","flags":1785950062} 33554432
```

Seems like something inside couchbase is storing the original passed value instead of what the transcoder is passing back. This also will need fixing for the users who do decide to use the transcoder.

**Comment by brett19** [comment]
Hey @AlmirKadric ,
Admittedly it might be useful to add some extra error notifications around this, but I suspect the reason you are seeing the document not being encoded properly is simply because you must pass a Buffer object back in the 'value' property of the return object.  Your `JSON.stringify` and "string type handling" both place a string object in the value property, you should wrap these in `new Buffer()` to ensure its returned as an already encoded buffer.
Cheers, Brett

**Comment by AlmirKadric** [comment]
Hi @brett19,
I made sure that a buffer was passed in using the code below and it works now:
```
var encoder = function (value) {
	var transcoderDoc;
	if (typeof value === 'string' || value instanceof String) {
		transcoderDoc = { value: new Buffer(value), flags: 0 };
	} else if (value instanceof Buffer) {
		transcoderDoc = { value: value, flags: 4 };
	} else {
		if (value.value && value.flags) {
			if (typeof value.value === 'string' || value.value instanceof String) {
				transcoderDoc = { value: new Buffer(value.value), flags: value.flags };
			} else if (value.value instanceof Buffer) {
				transcoderDoc = { value: value.value, flags: value.flags };
			} else {
				transcoderDoc = { value: new Buffer(JSON.stringify(value.value)), flags: value.flags };
			}
		} else {
			try {
				transcoderDoc = { value: new Buffer(JSON.stringify(value)), flags: 2 };
			} catch (error) {
				// TODO: NEED BETTER ERROR HANDLING HERE
				// NOTE: CHECK COUCHNOE NATIVE C CODE: `src/transcoder.cc`
				return;
			}
		}
	}

	console.log('ENCODER DOC:', transcoderDoc);
	return transcoderDoc;
};
var decoder = function (transcoderDoc) {
	console.log('DECODER DOC:', transcoderDoc);
	console.log('DECODER DOC:', (transcoderDoc.value || '').toString(), transcoderDoc.flags);
	return transcoderDoc;
};
_client.setTranscoder(encoder, decoder);
```

However this for us is not a viable solution. Rather than leveraging a feature of couchbase, we are hacking around the transcoder feature which does not do what we want it to. And the larger issue being that now we are passing in value options via the value and getting them back that way as well. This heavily changes the couchnode get/set/add/mget/mset apis.

Could you please explain to me what potential issues my original solution would raise and why this cannot be a feature inside the API itself (especially if it is only optional)?

**Comment by brett19** [comment]
Hey @AlmirKadric,
I am working on adding new features to the transcoder functionality.  I am going to adjust it so that the transcoder receives all passed to the invoking storage/retrieval operation.  This will allow you to do your own logic as needed of verifying if the `flags` option was passed, and if so, to handle it appropriately.  Does this sound like it would be a reasonable solution?
P.S. I also am fixing the transcoder invoker so that exceptions are propagated accurately and that incorrectly behaving transcoders cause errors rather than invisible fallback behaviour it currently has.
Cheers, Brett

**Comment by AlmirKadric** [comment]
Hi @brett19 ,
Provided that the originally intended API format does not change (i.e. we can pass flags via the options parameter, rather than through the value parameter), this would be fine for us.

Also please make sure that there is a mechanism for passing back flags when a value is retrieved without needing the transcoder hack.

RE: Error handling, this would be greatly appreciated ^_^
P.S. Please let me know if there is anything I can do to help.

Regards,
Almir Kadric

**Comment by brett19** [comment]
Gerrit relies on single contained commits representing single changes to the
code base for it's review process.  Your pull request however contains more
than a single commit.  Please squash your pull request down to a single commit
or split it into multiple pull requests so that we can process it!

::SDKBOT/PR:too_many_commits

**Comment by AlmirKadric** [comment]
Hi @brett19,
Just to confirm, for the above fixes you mentioned you would do to make the transcoder more usable and less hackish. What is the expected timeline? When do you think we will be able to begin using it?

We're quite eager to see this resolved as it is the last of the fixed needed for a big refactoring on our side to get node 5 support. If there is anything I can do to help expedite the situation please let me know.

Regards,
Almir Kadric

**Comment by brett19** [comment]
@AlmirKadric Have you considered writing a small wrapper around the Bucket class in the Node.js SDK to do what you are looking for? Trying to implement the behaviour we discussed turned out to be quite challenging to do without affecting the overall logic and performance of the SDK.

**Pull request closed without merging**
