### PR TITLE
Updated to libcouchbase 2.5.8 - Fixes "Got memcached EINVAL!".

### PR DESCRIPTION
**Pull request by djfm**
Hi,

My couchbase-backed hapi server kept crashing with "Got memcached EINVAL!" as described [on the couchbase forums](https://forums.couchbase.com/t/got-memcached-einval-aborted-core-dumped/7535).

According to [a link in the forum thread above](https://issues.couchbase.com/browse/CCBC-689) the issue was coming from libcouchbase and has been fixed in version 2.5.8.

So I've updated the dependency in couchnode to libcouchbase 2.5.8, and it solved my issue.

To be honest, I don't perfectly understand what I did, being quite unfamiliar with node-gyp :)

That being said, I've been able to run the test suite successfully both before and after the update of the dependency (using the real bucket, too), so I guess this contribution is at least a good base for discussion.

Let me know what you think!

### CODE REVIEW

**Comment by jezell** [comment]
Please merge this. Really annoying that a bug that causes the entire node process to crash and can be fixed simply by updating to the latest libcouchbase is not getting priority.

**Comment by ingenthr** [comment]
Hi @jezell; we have a monthly maintenance cadence and @brett19 will likely get to this very soon, which will let us run it through the test cycle for a June update.  Thanks!

**Comment by brett19** [comment]
Hey @jezell,
Keep in mind that you can always use your own copy of libcouchbase when installing couchnode using the --couchbase-root option as well.  Additionally, we will be upgrading libcouchbase to 2.6.0 for our next Node.js release (2.1.7).
Cheers, Brett

**Comment by jezell** [comment]
Thanks guys

**Pull request closed without merging**
