### PR TITLE
queuePush with createQueue option doesn't create the queue

### PR DESCRIPTION
**Pull request by vintagepx**
Pass the right variable to listPrepend call in queuePush

### CODE REVIEW

**Comment by brett19** [comment]
Hey @vintagepx ,
Thanks for the PR!  Change looks good, but would you be able to update the commit message to follow the standard message formatting we use?  I'll merge it right away afterwards.
Cheers, Brett

**Comment by vintagepx** [comment]
Done!

**Comment by brett19** [comment]
Hey @vintagepx,
It looks like something went wrong with the PR!  It has become a bunch of individual commits now.  Would you be able to fix that up?
Cheers, Brett

**Comment by vintagepx** [comment]
Only one commit now @brett19!
Sorry, I'm pretty noob with git and I'm not use to make even simple PRs.

**Pull request closed without merging**
