### PR TITLE
Switch from JSHint to ESlint

### PR DESCRIPTION
**Pull request by corbinu**
ESlint is a newer pluggable linter that does both the job of JSHint and JSCS (the JSCS team has actually joined the ESLint team) 

This PR is both a translation of the existing JSHint rules and a set of fixes based on issues found. It is structured so that if there is a rule you want changed it should be easy for me to rollback the commit and update the .eslintrc

Let me know if you have any questions or want any rule changes

### CODE REVIEW

**Comment by corbinu** [comment]
Your robot appears to be broken when I go to gerrit it says Agreement already submitted.

**Comment by corbinu** [comment]
@brett19 can you look into what might be wrong with cb-sdk-robot?

**Comment by brett19** [comment]
@corbinu Usually this means that your email address used for the commit author doesn't match what you have registered in Gerrit.  If you want to take a look and fix that, that would be awesome.
Thanks, Brett

**Comment by corbinu** [comment]
@brett19 I am sorry but I don't have an openID or a launchpadID and yes my email with github is different from from my git commit ID but we use Gitlab internally and don't want to mess up my work commits there either by changing it. I will see if there is something I can do, but this is not an easy process.

**Comment by ingenthr** [comment]
@corbinu you should be able to add your email address at http://review.couchbase.org/#/settings/contact after logging in.  It's also accessible from clicking on your name in the upper right, settings -> contact information.

**Comment by corbinu** [comment]
@ingenthr Thanks done!

**Comment by corbinu** [comment]
Recreated https://github.com/couchbase/couchnode/pull/62

**Pull request closed without merging**
